server:
  port: 8082

spring:
  application:
    name: upload-service
  servlet:
    multipart:
      # 限制文件上传的大小
      max-file-size: 5MB


# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
    instance-id: "${eureka.instance.ip-address}:${spring.application.name}:${server.port}"

logging:
  level:
    com.leyou.upload: debug

fdfs:
  so-timeout: 2500
  connect-timeout: 600
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: # tracker地址
  - 192.168.56.101:22122

ly:
  upload:
    baseUrl: http://image.leyou.com/
    allowTypes:
    - image/jpeg
    - image/png
    - image/bmp